[package]
name = "aisdk-macros"
version = "0.2.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.66"
syn = { version = "2.0", features = ["full", "parsing", "extra-traits"] }
quote = "1.0"
serde = {version = "1.0.219", features = ["derive"]}
schemars = "1.0.4"
